[package]
name = "polus"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonrpsee = "0.25.1"
lazy_static = "1.5.0"
"libc" = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
enum_util = { path = "../polus_utils/enum_util" }