[package]
name = "enum_util"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = {version = "1.0", features = ["full"]}
quote = "1.0"
proc-macro2 = "1.0"
anyhow = "1.0.99"

[lib]
proc-macro = true
